"""initial schema

Revision ID: ee03173cbb0a
Revises: 57e2ffaa40e9
Create Date: 2025-05-10 12:53:05.543429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee03173cbb0a'
down_revision: Union[str, None] = '57e2ffaa40e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=1000),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
