AUTH_TOKEN_TYPE = "Bearer"
AUTH_ACCESS_TOKEN_EXPIRE_MINUTE  = 1440
AUTH_REFRESH_TOKEN_EXPIRE_DAY  = 10
AUTH_VERIFICATION_TOKEN_EXPIRE_MINUTES= 1440
AUTH_TOKEN_ALGORITHM = "HS256"
AUTH_TOKEN_SECRET_KEY = "SECRET"
AUTH_USER_INACTIVE_TIMEOUT = 900